export const SET_BANNER = 'SET_BANNER';
export const REMOVE_BANNER = 'REMOVE_BANNER';
export const SET_CONGRATS_BANNER = 'SET_CONGRATS_BANNER';
export const REMOVE_CONGRATS_BANNER = 'REMOVE_CONGRATS_BANNER'